name: Lint

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install ruff mypy --frozen
      - name: ruff
        run: |
          ruff --version
          ruff check src
          ruff format src --check
      - name: mypy
        run: |
          mypy --version
          rm -rf .mypy_cache
          mypy -p matgl
